config/routes.rb
Rails.application.routes.draw do
  root "roles#index"
  resources :users do
    collection do
      get '/show_users' => 'users#show_users_based_on_roles'
    end
  end
  resources :roles do
    collection do
      get '/hide_roles' => 'roles#hide_roles'
      post '/update_hide_roles' => 'roles#update_hide_roles'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users
  validates :role_type, presence: true
end

app/models/roles_user.rb
class RolesUser < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  has_and_belongs_to_many :roles, dependent: :destroy
  has_many :user_metas, dependent: :destroy
  accepts_nested_attributes_for :user_metas
  has_many_attached :images
end

app/models/user_meta.rb
class UserMeta < ApplicationRecord
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]

  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: 'Role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def hide_roles
    @roles = Role.all
  end

  def update_hide_roles
    Role.all.update_all(hidden: false)
    Role.where(id: params[:role_ids]).update_all(hidden: true)
    RolesUser.where(role_id: params[:role_ids]).destroy_all
    respond_to do |format|
      format.html { redirect_to roles_path, notice: 'Roles hidden successfully.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.require(:role).permit(:role_type, :hidden)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :set_roles, only: [:index, :new, :edit]

  # GET /users
  # GET /users.json
  def index
    @users = User.includes(:roles).all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      @user.roles.destroy_all
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def show_users_based_on_roles
    @users = User.all.select{ |u| u.roles.blank? }.pluck(:email, :first_name, :last_name)
    respond_to do |format|
      format.html { }
      format.json { render json: {users: @users} }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def set_roles
      @roles = Role.where(hidden: false)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :first_name, :last_name, images: [], role_ids: [], user_metas_attributes: [:id, :meta_key, :meta_value, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LotvueTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
  </head>

  <body>
    <div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Logo</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <% hide_roles_action = params[:action] == 'hide_roles' %>
          <% show_users_action = params[:action] == 'show_users_based_on_roles' %>
          <li class="nav-item <%= (params[:controller] == 'roles' && !hide_roles_action) ? 'active' : '' %>">
            <a class="nav-link" href="<%= roles_path %>">Roles <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item <%= (params[:controller] == 'roles' && hide_roles_action) ? 'active' : '' %>">
            <a class="nav-link" href="<%= hide_roles_roles_path %>">Hide Roles <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item <%= (params[:controller] == 'users' && !show_users_action) ? 'active' : '' %>">
            <a class="nav-link" href="<%= users_path %>">Users <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item <%= (params[:controller] == 'users' && show_users_action) ? 'active' : '' %>">
            <a class="nav-link" href="<%= show_users_users_path %>">Show users <span class="sr-only">(current)</span></a>
          </li>
        </ul>
      </div>
    </nav>
    </div>
    <%= yield %>
    <%= yield :javascript_includes %>
  </body>
</html>

app/views/roles/_form.html.erb
<%= form_with(model: role, local: true) do |form| %>
  <% if role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% role.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-6">

      <div class="form-group">
        <%= form.label :role_type %>
        <%= form.text_field :role_type, class: "form-control", placeholder: "Enter role type" %>
      </div>

      <div class="actions">
        <%= form.submit 'Submit', class: "btn btn-success float-left" %>
        <%= link_to 'Back', roles_path, class: "btn btn-primary float-right"  %>
      </div>

    </div>
  </div>
<% end %>

app/views/roles/edit.html.erb
<div class="container">
  <div class="page-header">
    <h3>Editing Role</h3>
  </div>
  <%= render 'form', role: @role %>
</div>

app/views/roles/hide_roles.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <%= form_tag(update_hide_roles_roles_path, :method => "post") do %>

        <% @roles.each do |role| %>
          <div class="form-group">
            <%= check_box_tag "role_ids[]", role.id, role.hidden %>
            <%= label_tag role.role_type %>
          </div>
        <% end %>

        <div class="actions">
          <%= submit_tag "Hide roles", class: "btn btn-success" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/roles/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<div class="float-left"><h3>Roles</h3></div>

<div class="float-right">
  <%= link_to 'New Role', new_role_path, :class => "btn btn-large btn-primary" %>
</div>

<table id="roles-table" class="table table-striped table-bordered" width="100%" cellspacing="0">
  <thead>
    <tr>
      <th>Role type</th>
      <th colspan="3"></th>
      <th style="display:none"></th>
      <th style="display:none"></th>
    </tr>
  </thead>

  <tbody>
    <% @roles.each do |role| %>
      <tr>
        <td><%= role.role_type %></td>
        <td><%= link_to 'Show', role %></td>
        <td><%= link_to 'Edit', edit_role_path(role) %></td>
        <td><%= link_to 'Destroy', role, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>

<% content_for :javascript_includes do %>
<script>
  $(document).ready(function() {
    $('#roles-table').DataTable({
      paging: true,
      columns: [
        null,
        {"orderable": false},
        {"orderable": false},
        {"orderable": false}
      ]
    });
  });
</script>
<% end %>

app/views/roles/new.html.erb
<div class="container">
  <div class="page-header">
    <h3>New Role</h3>
    <%= render 'form', role: @role %>
  </div>

app/views/roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Role type:</strong>
  <%= @role.role_type %>
</p>

<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
  <div class="col-md-6">
    <div class="form-group">
      <%= f.label :email %>
      <%= f.text_field :email, class: "form-control", placeholder: "Enter email" %>
    </div>

    <div class="form-group">
      <%= f.label :first_name %>
      <%= f.text_field :first_name, class: "form-control", placeholder: "Enter first name" %>
    </div>

    <div class="form-group">
      <%= f.label :last_name %>
      <%= f.text_field :last_name, class: "form-control", placeholder: "Enter last name" %>
    </div>

    <div class="form-group">
      <%= label_tag :role %>
      <%= select_tag "user[role_ids][]", options_from_collection_for_select(@roles, "id", "role_type", @user.roles.ids), multiple: true, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.fields_for :user_metas do |user_meta| %>
        <%= render 'user_meta_fields', :f => user_meta %>
      <% end %>
      <p><%= link_to_add_association 'Add a User Meta', f, :user_metas %></p>
    </div>

    <div class="form-group">
      <%= label_tag :images %>
      <%= f.file_field :images, accept: 'image/png,image/jpeg', :multiple => true, class: "form-control-file" %><br>
    </div>

    <div class="actions">
      <%= f.submit 'Submit', class: "btn btn-success float-left" %>
      <%= link_to 'Back', users_path, class: "btn btn-primary float-right" %>
    </div>
  </div>
</div>
<% end %>

app/views/users/_user_meta_fields.html.erb
<div class="form-group">
  <%= f.label :meta_key %>
  <%= f.text_field :meta_key, class: "form-control", placeholder: "Enter meta key" %>
</div>
<div class="form-group">
  <%= f.label :meta_value %>
  <%= f.text_field :meta_value, class: "form-control", placeholder: "Enter meta value" %>
</div>
<%= link_to_remove_association "Remove user meta", f %>

app/views/users/edit.html.erb
<div class="container">
  <div class="page-header">
    <h3>Editing User</h3>
  </div>
  <%= render 'form', user: @user %>
</div>

app/views/users/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-12">
<div class="float-left"><h3>Users</h3></div>

<div class="float-right">
  <%= link_to 'New User', new_user_path, :class => "btn btn-large btn-primary" %>
</div>
</div>
</div>


<div class="row">
  <div class="col-md-12">
    <div class="form-group row">
      <label for="role_filter" class="col-sm-3 col-form-label">Filter Based on Role</label>
      <div class="col-sm-9">
        <select class="form-control" id="role_filter">
          <option></option>
          <% @roles.each do |role| %>
            <option value="<%= role.role_type %>"><%= role.role_type %></option>
            <% end %>
          </select>
      </div>
    </div>
  </div>
</div>

<table id="users-table" class="table table-striped table-bordered" width="100%" cellspacing="0">
  <thead>
    <tr>
      <th>Images</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Roles</th>
      <th colspan="3"></th>
      <th style="display:none"></th>
      <th style="display:none"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td>
          <% user.images.each do |file| %>
            <%= image_tag url_for(file), size: "100x100" %>
          <% end %>
        </td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.roles.pluck(:role_type).join(', ') %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>

<% content_for :javascript_includes do %>
<script>
  $(document).ready(function() {
    usersTable = $('#users-table').DataTable({
      paging: true,
      columns: [
        {"orderable": false},
        null,
        null,
        null,
        {"orderable": false},
        {"orderable": false},
        {"orderable": false}
      ]
    });


$.fn.dataTable.ext.search.push(
    function( settings, data, dataIndex ) {
        var selected_role = $( "#role_filter" ).val();
        var role = data[3] || ''; // use data for the age column
        if(role.includes(selected_role)) {
            return true;
        }
        return false;
    }
);

    $('#role_filter').on('change', function(){
        usersTable.draw();
    });

  });


</script>
<% end %>

app/views/users/new.html.erb
<div class="container">
  <div class="page-header">
    <h3>New User</h3>
    <%= render 'form', user: @user %>
  </div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

  <% @user.user_metas.each do |user_meta| %>
  <p>
    <strong><%= user_meta.meta_key.capitalize %>:</strong>
    <%= user_meta.meta_value.capitalize %>
  </p>
  <% end %>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/show_users_based_on_roles.html.erb
<div class="container">

<div class="float-left"><h3>Show Users</h3></div>

<table id="show-users-table" class="table table-striped table-bordered" width="100%" cellspacing="0">
  <thead>
    <tr>
      <th>Email</th>
      <th>First name</th>
      <th>Last name</th>
    </tr>
  </thead>

  <tbody>
  </tbody>
</table>

</div>

<% content_for :javascript_includes do %>
<script>
$(document).ready(function() {
  $.ajax({
    type: 'get',
    url: '<%= show_users_users_path %>',
    dataType: "json",
    success: function (result) {
      console.log(result);
      result["users"].map(function(user) {
        $('#show-users-table thead').append("<tr><td>" + user[0] + "</td><td>" + user[1] + "</td><td>" + user[2] + "</td></tr>");
      })
    },
    error: function () {
      console.log("Failed to fetch users!");
    }
  });
});
</script>
<% end %>